### ISSUE TITLE
Containership docs are missing

### ISSUE THREAD

**Issue by dimitrovskif** [containership/containership-docs#2]
https://docs.containership.io/docs/installation

All the pages are empty.

**Comment by dimitrovskif** [comment]
It seems there is a JavaScript error that stops docs rendering:
```
Error: JSON.parse: bad control character in string literal at line 1 column 98 of the JSON data
```

Ping @normanjoyner

**Comment by normanjoyner** [comment]
@dimitrovskif this repo is actually outdated as we moved our docs to readme.io; however, thank you for the bug report! It seems like this is happening when logged into the site. When I opened the docs in a private tab everything loaded fine. Can you confirm?

**Comment by dimitrovskif** [comment]
I don't know how you managed to test that (especially since the JavaScript error makes the UI think you are logged out) - but yes! That fixed the issue.

I've just started using containership and you solved so many problems, thanks! I might switch to a paid cloud plan when the software matures a bit.

**Comment by normanjoyner** [comment]
@dimitrovskif glad I could help! Let me know if you have any other questions!

**Comment by dimitrovskif** [comment]
@normanjoyner 

There is a dead link in https://docs.containership.io/docs/setting-up-your-first-cluster
> A more in depth explanation of the CLI is available **here**.

Also, off-topic (I guess it's OK since this repo is dead), is it a bug if a follower doesn't deploy more than 3 containers? No matter how I scale apps, the sum is always max 3

**Comment by normanjoyner** [comment]
Thanks! The dead link should be resolved.

You should check the logs on the leader and follower nodes to see if there is a message regarding a failed container placement. If you are not already, you can set `--log-level=debug` for more verbose messages.

If you are running the navigator plugin you should be able to see available cluster resources on /. Additionally, you can see the resources available for a specific node by going to the hosts page and clicking the desired follower. It's possible you are out of available resources, so the container is unable to be placed.
